#Backend CI/CD Pipeline
name: CI/CD Backend
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      - name: Deploy
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USERNAME : ${{secrets.SSH_USERNAME}}
        run: |
          sshpass -p "${SSH_KEY}" ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} << 'EOF'
          cd /var/www/large-project/
          git pull origin main
          sudo rm -rf /var/server/*
          sudo cp server.js package.json package-lock.json /var/server/
          cd /var/server/
          npm install
          pm2 restart server.js
          EOF