#Frontend CI/CD Pipeline
name: CI/CD
on:
  pull_request:
    branches:
      - master
    push:
      branches:
      - master
    jobs:
      deploy_backend:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Install dependencies
            run: npm install
          - name: Deploy
            env:
              SSH_HOST: ${{ secrets.SSH_HOST }}
              SSH_KEY: ${{ secrets.SSH_KEY }}
              SSH_USERNAME : ${{secrets.SSH_USERNAME}}
              run: |
                sshpass -p "${SSH_KEY}" ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} << 'EOF'
                cd Ganttify/Ganttify-Backend-UCF_SD
                git pull origin master
                npm install
                pm2 restart server
                EOF

                #frontend CI/CD Pipeline

#Backend CI/CD Pipeline 
name: CI/CD Pipeline 
on: 
  push: 
    branches:
      - master
    pull_request:
      branches: 
        - master

      jobs:
        build:
          runs-on: ubuntu-latest
          steps: 
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '22.17.0'
            - name: Install dependencies
              run: npm install
        deploy: 
          needs: build
          runs-on: ubuntu-latest
          steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install sshpass
              run: sudo apt-get install -y sshpass
            - name: Deploy to DigitalOcean Droplet
              env:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
                SSH_HOST: ${{ secrets.SSH_HOST }}
              run: |
                sshpass -p "${SSH_KEY}" ssh -o StrictHostKeyChecking=no ${SSH}_USERNAME}@${SSH_HOST} << 'EOF'
                cd /var/www/html
                git pull origin main
                npm install
                npm run build
                systemctl restart nginx
                EOF