name: Remote Deployment
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      - name: Deploy to server
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          sshpass -p "${SSH_KEY}" ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} << 'EOF'
          cd /var/www/large-project/
          git pull origin main
          sudo rm -rf /var/server/*
          sudo cp -r backend/. /var/server/
          cd /var/server/
          npm install
          pm2 restart server.js
          cd /var/www/large-project/frontend/
          npm install
          npm run build
          sudo rm -rf /var/www/html/*
          sudo cp -r dist/* /var/www/html/
          systemctl restart nginx
          EOF