name: Remote Deployment
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      - name: Deploy to server
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          sshpass -p "${SSH_KEY}" ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} << 'EOF'
          cd /var/www/large-project/
          git restore .
          git pull origin main
          cd backend/
          npm install
          pm2 restart server.js
          cd /var/www/large-project/
          cp nginx.conf /etc/nginx/sites-available/default
          nginx -s reload
          cd frontend/
          rm -rf dist/
          npm install
          npm run build
          systemctl restart nginx
          EOF
